[package]
name = "tank-e"
version = "0.1.0"
edition = "2024"

[dependencies]
rppal = "0.22.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
snafu = "0.8.9"
tungstenite = "0.28.0"
